CREATE TABLE role_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE task_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    complete BOOLEAN NOT NULL,
    create_date TIMESTAMP(6) WITH TIME ZONE,
    end_date TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT,
    description VARCHAR(255),
    task_name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_role_tbl (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE user_tbl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE task_tbl 
    ADD CONSTRAINT fk_task_user
    FOREIGN KEY (user_id) 
    REFERENCES user_tbl(id)
    ON DELETE SET NULL;

ALTER TABLE user_role_tbl 
    ADD CONSTRAINT fk_role
    FOREIGN KEY (role_id) 
    REFERENCES role_tbl(id)
    ON DELETE CASCADE;

ALTER TABLE user_role_tbl 
    ADD CONSTRAINT fk_user 
    FOREIGN KEY (user_id) 
    REFERENCES user_tbl(id)
    ON DELETE CASCADE;
