CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    complete BOOLEAN NOT NULL,
    create_date TIMESTAMP(6) WITH TIME ZONE,
    end_date TIMESTAMP(6) WITH TIME ZONE,
    user_id BIGINT,
    description VARCHAR(255),
    name VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE user_role (
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    login VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE task 
    ADD CONSTRAINT fk_task_user
    FOREIGN KEY (user_id) 
    REFERENCES app_user(id)
    ON DELETE SET NULL;

ALTER TABLE user_role 
    ADD CONSTRAINT fk_role
    FOREIGN KEY (role_id) 
    REFERENCES role(id)
    ON DELETE CASCADE;

ALTER TABLE user_role 
    ADD CONSTRAINT fk_user 
    FOREIGN KEY (user_id) 
    REFERENCES app_user(id)
    ON DELETE CASCADE;
